/**
 * PDF.
 *
 * PDF is a page-description format, not a document format: it stores glyph-drawing
 * instructions, and "the text" is something you reconstruct rather than read. A complete
 * implementation needs font encoding tables, CMap parsing and layout reconstruction, which
 * is why every real PDF library is large.
 *
 * This extracts text from the common case — a PDF generated by Word, LaTeX or a browser,
 * with Flate-compressed content streams and standard encodings. That covers a good share of
 * résumés and nothing else.
 *
 * Where it does **not** work it says so and stops. A scanned résumé is an image and needs
 * OCR; a PDF using custom font encodings yields mojibake. Returning that as extracted
 * content would put garbage on someone's portfolio under the label "from your résumé",
 * which is worse than extracting nothing — so the output is sanity-checked, and a failure
 * points at .docx, which this project reads properly.
 *
 * The importer interface is the point of this file. Replacing it with a real PDF pipeline
 * later touches nothing outside this module.
 *
 * @module core/documents/importers/pdf
 */

import { parseResumeLines } from '../resume-text.js'

/** @type {import('../types.js').DocumentImporter} */
const pdfImporter = {
  id: 'pdf',
  name: 'PDF',
  extensions: ['.pdf'],
  method: 'text',
  limits:
    'Handles text-based PDFs with standard encodings. Scanned PDFs are images and need OCR; '
    + 'PDFs with embedded custom font encodings cannot be decoded. Exporting your résumé as '
    + '.docx or .md gives markedly better results.',

  detect: (input) => Boolean(input.bytes && startsWith(input.bytes, '%PDF-')),

  async extract(input, ctx) {
    if (!input.bytes) return { ok: false, reason: 'No file content was provided.' }
    const buffer = Buffer.from(input.bytes)

    if (!startsWith(input.bytes, '%PDF-')) {
      return { ok: false, reason: 'This file is not a PDF (it does not begin with %PDF-).' }
    }

    if (/\/Encrypt\b/.test(buffer.toString('latin1', 0, Math.min(buffer.length, 4096)))) {
      return {
        ok: false,
        reason: 'This PDF is encrypted, so its text cannot be read.',
        hint: 'Remove the password, or export the document as .docx or .md.',
      }
    }

    let pages
    try {
      pages = await extractPages(buffer)
    } catch (err) {
      return { ok: false, reason: `The PDF could not be parsed: ${/** @type {Error} */ (err).message}` }
    }

    const text = pages.map((page) => page.text).join('\n')

    if (!text.trim()) {
      return {
        ok: false,
        reason: 'No text could be extracted. This PDF is most likely a scan, so its content is an image.',
        hint: 'Run it through OCR, or export the original document as .docx or .md and import that.',
      }
    }

    if (!looksLikeProse(text)) {
      // Custom font encodings decode to plausible-looking bytes that are not the document's
      // words. Shipping those as "extracted from your résumé" would be fabrication.
      return {
        ok: false,
        reason: 'Text was found but could not be decoded — this PDF uses embedded font encodings this reader cannot map.',
        hint: 'Export the document as .docx or .md and import that instead.',
      }
    }

    /** @type {import('../resume-text.js').Line[]} */
    const lines = []
    for (const page of pages) {
      for (const raw of page.text.split(/\r?\n/)) {
        const trimmed = raw.trim()
        if (!trimmed) continue
        // PDFs carry no heading markup, so headings are left for the text parser to infer.
        lines.push({ text: trimmed, index: lines.length, page: page.number, heading: false })
      }
    }

    const { profile, evidence, warnings } = parseResumeLines(lines, {
      documentId: ctx.documentId,
      filename: input.filename,
    })

    return {
      ok: true,
      document: {
        meta: {
          id: ctx.documentId,
          filename: input.filename,
          type: ctx.type,
          mediaType: 'application/pdf',
          importedAt: new Date(ctx.now).toISOString(),
          extraction: 'text',
          extractor: 'pdf@1.0',
          bytes: input.bytes.length,
          pages: pages.length,
        },
        profile,
        evidence,
        warnings: [
          'Text was reconstructed from PDF drawing instructions, so it is the least reliable '
          + 'import route. Check the imported values before publishing.',
          ...warnings,
        ],
      },
    }
  },
}

/**
 * Pull text out of each content stream.
 *
 * Streams are located by scanning for `stream`/`endstream` rather than by walking the xref
 * table: the xref may be a cross-reference *stream* in newer PDFs, and may be wrong in files
 * that have been incrementally updated. Scanning is cruder but degrades to "found fewer
 * streams" rather than to "failed to parse".
 *
 * @param {Buffer} buffer
 * @returns {Promise<{number: number, text: string}[]>}
 */
async function extractPages(buffer) {
  const zlib = await import('node:zlib')
  const latin = buffer.toString('latin1')

  const pages = []
  let cursor = 0
  let pageNumber = 0

  for (;;) {
    const start = latin.indexOf('stream', cursor)
    if (start === -1) break
    const end = latin.indexOf('endstream', start)
    if (end === -1) break

    // The keyword is followed by CRLF or LF, and the data begins immediately after.
    let from = start + 'stream'.length
    if (latin[from] === '\r') from += 1
    if (latin[from] === '\n') from += 1

    const raw = buffer.subarray(from, end)
    cursor = end + 'endstream'.length

    // Only the dictionary immediately preceding the stream describes it.
    const header = latin.slice(Math.max(0, start - 400), start)
    if (/\/Image\b|\/DCTDecode\b|\/JPXDecode\b/.test(header)) continue

    let content = raw
    if (/\/FlateDecode\b/.test(header)) {
      try {
        content = zlib.inflateSync(raw)
      } catch {
        // Some producers pad streams; retry tolerantly before giving up on this one.
        try {
          content = zlib.inflateSync(raw, { finishFlush: zlib.constants.Z_SYNC_FLUSH })
        } catch {
          continue
        }
      }
    } else if (/\/(LZW|RunLength|CCITTFax|JBIG2)Decode\b/.test(header)) {
      continue
    }

    const text = textFromContentStream(content.toString('latin1'))
    if (!text.trim()) continue

    pageNumber += 1
    pages.push({ number: pageNumber, text })
  }

  return pages
}

/**
 * Read the text-showing operators out of a content stream.
 *
 * `(string) Tj` and `[(a) -250 (b)] TJ` draw text; `Td`/`TD`/`T*`/`'`/`"` move the cursor,
 * which is how line breaks are inferred, since a PDF has no newline character.
 *
 * @param {string} content
 * @returns {string}
 */
function textFromContentStream(content) {
  const out = []
  let line = []

  const flush = () => {
    if (line.length) { out.push(line.join('')); line = [] }
  }

  // Matches: a literal string, an array of them, or a positioning operator.
  const token = /\((?:\\.|[^\\()])*\)|\[[^\]]*\]|\bT[dD*]\b|\bTJ\b|\bTj\b|\bT[fLwz]\b|'|"/g
  let match
  let pending = null

  while ((match = token.exec(content))) {
    const value = match[0]

    if (value.startsWith('(')) { pending = [decodeLiteral(value)]; continue }

    if (value.startsWith('[')) {
      const parts = [...value.matchAll(/\((?:\\.|[^\\()])*\)|-?\d+(?:\.\d+)?/g)].map((m) => m[0])
      const assembled = []
      for (const part of parts) {
        if (part.startsWith('(')) { assembled.push(decodeLiteral(part)); continue }
        // A large negative kern is the PDF idiom for a word space.
        if (Number(part) <= -180) assembled.push(' ')
      }
      pending = assembled
      continue
    }

    if (value === 'Tj' || value === 'TJ' || value === "'" || value === '"') {
      if (pending) line.push(pending.join(''))
      pending = null
      if (value === "'" || value === '"') flush()
      continue
    }

    if (value === 'Td' || value === 'TD' || value === 'T*') flush()
  }

  flush()
  return out.join('\n')
}

/**
 * Decode a PDF literal string: `\n` style escapes, and `\ddd` octal.
 * @param {string} literal
 */
function decodeLiteral(literal) {
  const body = literal.slice(1, -1)
  return body.replace(/\\(n|r|t|b|f|\(|\)|\\|[0-7]{1,3})/g, (_, escape) => {
    switch (escape) {
      case 'n': return '\n'
      case 'r': return '\r'
      case 't': return '\t'
      case 'b': return '\b'
      case 'f': return '\f'
      case '(': return '('
      case ')': return ')'
      case '\\': return '\\'
      default: return String.fromCharCode(parseInt(escape, 8))
    }
  })
}

/**
 * Whether the extracted text is plausibly the document's words.
 *
 * A PDF with custom font encodings decodes to bytes that are *valid characters* but not the
 * right ones, so the check is on shape: real prose is mostly letters, spaces and common
 * punctuation. This is the guard that stops mojibake being published as someone's
 * experience.
 *
 * @param {string} text
 */
function looksLikeProse(text) {
  const sample = text.slice(0, 4000)
  if (sample.replace(/\s/g, '').length < 20) return false

  const readable = (sample.match(/[A-Za-z0-9 .,;:'"()&/@+-]/g) ?? []).length
  const ratio = readable / sample.length
  if (ratio < 0.8) return false

  // Real text contains words; encoding failures rarely produce runs of letters.
  return /[A-Za-z]{3,}\s+[A-Za-z]{3,}/.test(sample)
}

/** @param {Uint8Array} bytes @param {string} prefix */
function startsWith(bytes, prefix) {
  if (bytes.length < prefix.length) return false
  for (let i = 0; i < prefix.length; i += 1) {
    if (bytes[i] !== prefix.charCodeAt(i)) return false
  }
  return true
}

export default pdfImporter
export { textFromContentStream, looksLikeProse }
