/**
 * The layered merge.
 *
 * The central guarantee of this project is that re-importing data never destroys anything
 * you wrote by hand. That is achieved by never mutating in place: the final profile is
 * recomputed from ordered layers on every build.
 *
 *   1. connector output   — disposable, regenerated by `npm run import`
 *   2. manual content     — hand-written records the connectors cannot know about
 *   3. user overrides     — field-level pins, hides and explicit ordering
 *
 * Later layers win. Crucially, they win *per field*: pinning a project's title still lets
 * the next import refresh its star count.
 *
 * @module core/schema/merge
 */

import { COLLECTIONS } from './types.js'
import { createEmptyProfile, normalizeProfile, slugify } from './profile.js'

/** @typedef {import('./types.js').Profile} Profile */

/**
 * A sparse set of user edits applied on top of merged data.
 *
 * @typedef {object} Overrides
 * @property {Record<string, unknown>} [identity]
 * @property {Record<string, Record<string, unknown>>} [records]
 *   Collection name → record id → partial record. Only the named fields are overridden.
 * @property {Record<string, string[]>} [hidden]
 *   Collection name → record ids to omit entirely.
 * @property {Record<string, string[]>} [order]
 *   Collection name → record ids in the order they should appear. Ids not listed keep
 *   their computed order and follow the pinned ones.
 * @property {Record<string, string>} [socials]
 */

/** True for a plain object (not null, not an array, not a Date). */
const isPlainObject = (v) =>
  v !== null && typeof v === 'object' && !Array.isArray(v) && !(v instanceof Date)

/**
 * Recursively merge `source` onto `target`.
 *
 * Arrays replace rather than concatenate: if a user writes `technologies: ["Rust"]` they
 * mean exactly that list, not that list appended to whatever was imported. `undefined`
 * values in `source` are skipped so a partial object only touches the fields it names,
 * while an explicit `null` clears a field.
 *
 * @template T
 * @param {T} target
 * @param {unknown} source
 * @returns {T}
 */
export function deepMerge(target, source) {
  if (!isPlainObject(source)) return /** @type {T} */ (source === undefined ? target : source)
  const base = isPlainObject(target) ? { ...(/** @type {object} */ (target)) } : {}
  const out = /** @type {Record<string, unknown>} */ (base)

  for (const [key, value] of Object.entries(/** @type {Record<string, unknown>} */ (source))) {
    // Never let untrusted JSON reach Object.prototype.
    if (key === '__proto__' || key === 'constructor' || key === 'prototype') continue
    if (value === undefined) continue
    if (value === null) { delete out[key]; continue }
    out[key] = isPlainObject(value) ? deepMerge(out[key], value) : value
  }
  return /** @type {T} */ (out)
}

/**
 * The key used to match "the same record" across layers.
 *
 * Prefers an explicit `id`, then falls back to a natural key derived from the fields that
 * actually identify the record. Without this, a hand-written experience entry and the
 * imported one for the same job would render twice.
 *
 * @param {string} collection
 * @param {Record<string, any>} record
 * @returns {string}
 */
export function recordKey(collection, record) {
  if (typeof record.id === 'string' && record.id) return record.id
  switch (collection) {
    case 'education':
      return slugify(record.institution, record.degree)
    case 'experience':
      return slugify(record.company, record.role)
    case 'competitive':
      return slugify(record.platform, record.username)
    case 'skills':
    case 'languages':
      return slugify(record.name)
    case 'packages':
      return slugify(record.registry, record.name)
    default:
      return slugify(record.name ?? record.title ?? record.platform)
  }
}

/**
 * Merge any number of profile-shaped layers into one profile. Later layers win.
 *
 * @param {...unknown} layers
 * @returns {Profile}
 */
export function mergeProfiles(...layers) {
  const result = createEmptyProfile()
  const normalized = layers.filter(Boolean).map((l) => normalizeProfile(l))

  for (const layer of normalized) {
    // `normalizeIdentity` always emits `name` (as `''` when absent) so that renderers never
    // see undefined. That makes it the one field a later layer can blank by accident, so
    // an empty name is treated as "not specified" rather than "set to empty".
    const previousName = result.identity.name
    result.identity = deepMerge(result.identity, layer.identity)
    if (!layer.identity.name && previousName) result.identity.name = previousName
    Object.assign(result.socials, layer.socials)
    result.meta = deepMerge(result.meta, layer.meta)
  }

  for (const collection of COLLECTIONS) {
    /** @type {Map<string, Record<string, any>>} */
    const byKey = new Map()
    for (const layer of normalized) {
      const records = /** @type {Record<string, any>[]} */ (layer[collection] ?? [])
      for (const record of records) {
        const key = recordKey(collection, record)
        const existing = byKey.get(key)
        byKey.set(key, existing ? deepMerge(existing, record) : { ...record })
      }
    }
    // @ts-expect-error — collections are homogeneous by construction.
    result[collection] = [...byKey.values()]
  }

  /** @type {Map<string, Map<string, Record<string, any>>>} */
  const customByKey = new Map()
  for (const layer of normalized) {
    for (const [name, records] of Object.entries(layer.custom ?? {})) {
      if (!customByKey.has(name)) customByKey.set(name, new Map())
      const bucket = /** @type {Map<string, Record<string, any>>} */ (customByKey.get(name))
      for (const record of records) {
        const key = recordKey('custom', record)
        const existing = bucket.get(key)
        bucket.set(key, existing ? deepMerge(existing, record) : { ...record })
      }
    }
  }
  for (const [name, bucket] of customByKey) {
    result.custom[name] = /** @type {any} */ ([...bucket.values()])
  }

  // Stats are always recomputed downstream; carrying them through a merge would let a
  // stale layer contribute a number that no longer has records behind it.
  result.stats = { entries: [] }

  return result
}

/**
 * Apply user overrides to a merged profile.
 *
 * Returns a new profile; the input is not mutated.
 *
 * @param {Profile} profile
 * @param {Overrides|undefined|null} overrides
 * @returns {Profile}
 */
export function applyOverrides(profile, overrides) {
  if (!overrides || typeof overrides !== 'object') return profile

  /** @type {Profile} */
  const out = { ...profile, identity: { ...profile.identity }, socials: { ...profile.socials } }

  if (isPlainObject(overrides.identity)) {
    const patch = normalizeProfile({ identity: overrides.identity }).identity
    // See `mergeProfiles` — an always-present empty `name` must not blank the real one.
    if (!patch.name) delete (/** @type {Record<string, unknown>} */ (patch)).name
    out.identity = deepMerge(out.identity, patch)
  }

  if (isPlainObject(overrides.socials)) {
    const patch = normalizeProfile({ socials: overrides.socials }).socials
    out.socials = { ...out.socials, ...patch }
  }

  const collections = /** @type {string[]} */ ([...COLLECTIONS])

  for (const collection of collections) {
    const records = /** @type {Record<string, any>[]} */ (out[/** @type {keyof Profile} */ (collection)] ?? [])
    if (!Array.isArray(records)) continue

    let next = records.map((r) => ({ ...r }))

    // Field-level pins.
    const patches = overrides.records?.[collection]
    if (isPlainObject(patches)) {
      // Normalize the patch through the schema so an override cannot smuggle in a
      // `javascript:` URL or an unmodelled field.
      const normalizedPatches = normalizeProfile({
        [collection]: Object.entries(patches).map(([id, patch]) => ({
          ...(isPlainObject(patch) ? patch : {}),
          id,
        })),
      })[/** @type {keyof Profile} */ (collection)]

      /** @type {Map<string, Record<string, any>>} */
      const patchById = new Map(
        (/** @type {Record<string, any>[]} */ (normalizedPatches) ?? []).map((p) => [p.id, p]),
      )

      next = next.map((record) => {
        const patch = patchById.get(recordKey(collection, record))
        if (!patch) return record
        patchById.delete(recordKey(collection, record))
        return deepMerge(record, patch)
      })

      // A patch whose id matches nothing is a user-authored record; keep it rather than
      // silently discarding what they typed.
      for (const orphan of patchById.values()) next.push(orphan)
    }

    // Hides.
    const hidden = overrides.hidden?.[collection]
    if (Array.isArray(hidden) && hidden.length) {
      const hiddenSet = new Set(hidden)
      next = next.filter((r) => !hiddenSet.has(recordKey(collection, r)))
    }

    // Explicit ordering — pinned ids first, everything else after in computed order.
    const order = overrides.order?.[collection]
    if (Array.isArray(order) && order.length) {
      const rank = new Map(order.map((id, i) => [id, i]))
      const pinned = []
      const rest = []
      for (const record of next) {
        const key = recordKey(collection, record)
        if (rank.has(key)) pinned.push(record)
        else rest.push(record)
      }
      pinned.sort((a, b) =>
        (rank.get(recordKey(collection, a)) ?? 0) - (rank.get(recordKey(collection, b)) ?? 0))
      next = [...pinned, ...rest]
    }

    // @ts-expect-error — collections are homogeneous by construction.
    out[collection] = next
  }

  return out
}
